// <auto-generated />
using Handshakes_Carpark.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace handshakes_carpark.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("Handshakes_Carpark.Models.CarPark", b =>
                {
                    b.Property<string>("CarParkNo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CarParkBasement")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarParkDecks")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CarParkType")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FavoriteCarPark")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("FreeParking")
                        .HasColumnType("TEXT");

                    b.Property<double>("GantryHeight")
                        .HasColumnType("REAL");

                    b.Property<bool>("NightParking")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParkingSystemType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortTermParking")
                        .HasColumnType("TEXT");

                    b.Property<double>("XCoord")
                        .HasColumnType("REAL");

                    b.Property<double>("YCoord")
                        .HasColumnType("REAL");

                    b.HasKey("CarParkNo");

                    b.ToTable("CarParks", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
